export type ContentBlock =
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "note"; text: string }
  | { type: "price-table"; headers: string[]; rows: string[][] }
  | { type: "cta"; text: string; href: string; subtext?: string }
  | { type: "related"; posts: { title: string; slug: string }[] }

export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  category: string
  date: string
  readTime: string
  featured: boolean
  metaTitle: string
  metaDescription: string
  targetKeyword: string
  coverImage?: string
  content: ContentBlock[]
  faq: { q: string; a: string }[]
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "no-uber-nassau-bahamas",
    title: "No Uber in Nassau, Bahamas — Here's What Tourists Actually Use in 2026",
    excerpt: "Uber and Lyft don't operate in Nassau. Here's the exact alternative — with fixed prices, pre-booking, and a safety net built for the Bahamas.",
    category: "Nassau Travel Guide",
    date: "May 5, 2026",
    readTime: "5 min read",
    featured: true,
    metaTitle: "No Uber in Nassau Bahamas (2026) — What to Use Instead | HOP",
    metaDescription: "Uber and Lyft don't operate in Nassau, Bahamas. Discover HOP — the local ride app with fixed fares, pre-booking, and real-time safety. Book before you land.",
    targetKeyword: "uber nassau bahamas",
    coverImage: "/images/dest-nassau.jpg",
    content: [
      { type: "p", text: "Uber doesn't operate in Nassau, Bahamas. Neither does Lyft. If you've already opened one of those apps on the island, you've discovered this the slightly annoying way. You're not alone — it's one of the most Googled transportation questions about the Bahamas, right up there with 'do they drive on the left?' (they do, by the way)." },
      { type: "h2", text: "Why Isn't Uber in Nassau?" },
      { type: "p", text: "Nassau's taxi market is government-regulated with fixed zone fares and a well-organized taxi union that's been running the roads for decades. Uber needs volume — Nassau has around 300,000 residents and a tourist season that's good but not NYC-good. The math hasn't worked out for them, and they haven't tried." },
      { type: "p", text: "The result: millions of visitors land at Lynden Pindling International Airport every year, reach for their Uber app, and get nothing. Not 'surge pricing' nothing. Just nothing." },
      { type: "h2", text: "Your Options for Getting Around Nassau" },
      { type: "price-table", headers: ["Option", "Pros", "Cons", "Best For"], rows: [
        ["Licensed Taxis", "Available at airport & port", "No posted prices, negotiation required", "Short trips if you like haggling"],
        ["Jitney (Public Bus)", "$1.25–$3.50 per ride", "Set routes only, no luggage space", "Solo travelers, downtown only"],
        ["Resort Shuttles", "Air-conditioned, reliable", "$38–$45 per person each way", "Resort guests who don't check prices"],
        ["Rental Car", "Full flexibility", "Left-side driving, limited parking", "4+ day stays"],
        ["HOP App", "Fixed fare shown upfront, pre-book before landing", "Nassau-only (it's made for here)", "Most tourists, most trips"],
      ]},
      { type: "h2", text: "HOP: The Ride App Built for Nassau" },
      { type: "p", text: "HOP is a Nassau-native ride app that works the same way Uber does — you open it, enter your destination, see a fare, confirm. Except the fare is fixed (no meters, no surge), you can book before your plane lands, and it runs on Low Data Mode when Nassau's mobile signal decides to take the day off." },
      { type: "ul", items: [
        "Fixed fares — the price you see is the price you pay",
        "Pre-book before you land — no taxi queue after a long flight",
        "No download required — the web app works in any browser",
        "Low Data Mode — stays functional on weak Nassau signal",
        "SOS system — one tap alerts emergency services and trusted contacts",
      ]},
      { type: "h2", text: "How to Book HOP Before You Arrive" },
      { type: "ol", items: [
        "Go to app.hopbahamas.com (or grab the iOS/Android app)",
        "Enter your pickup: Lynden Pindling International Airport, Terminal A",
        "Enter your destination: Atlantis, Baha Mar, your hotel address",
        "See your fixed fare — confirmed before you commit",
        "Choose pickup date and time — book for when your flight actually lands",
        "Pay by card or cash — both work fine",
      ]},
      { type: "note", text: "Pro move: Book your airport pickup before you board your flight home. Nassau's airport is busy and having a confirmed driver means you walk out of arrivals instead of joining the taxi queue." },
      { type: "h2", text: "How Much Does It Cost?" },
      { type: "p", text: "HOP fares are fixed and visible before you confirm. Here's how the most common routes compare:" },
      { type: "price-table", headers: ["Route", "HOP Fixed Fare", "Standard Taxi Fare"], rows: [
        ["LPIA Airport → Atlantis", "$28", "$45–$55"],
        ["LPIA Airport → Baha Mar", "from $22", "$30–$40"],
        ["LPIA Airport → Cable Beach", "from $22", "$28–$36"],
        ["LPIA Airport → Downtown Nassau", "from $20", "$32–$40"],
        ["Cruise Port → Atlantis", "from $18", "$20–$30"],
        ["Cruise Port → Cable Beach", "from $18", "$18–$24"],
      ]},
      { type: "related", posts: [
        { title: "Nassau Bahamas Taxi Fares 2026 — The Official Prices (No Surprises)", slug: "nassau-taxi-cost-guide-2026" },
        { title: "How to Get Around Nassau Bahamas in 2026 — Every Option Explained", slug: "how-to-get-around-nassau-bahamas" },
      ]},
      { type: "cta", text: "Book My Ride — No Download Needed", href: "https://app.hopbahamas.com", subtext: "See your fixed fare before you commit. Free cancellation." },
    ],
    faq: [
      { q: "Is there Uber in Nassau, Bahamas?", a: "No. Uber and Lyft do not operate in Nassau, Bahamas. The closest equivalent is HOP — a Nassau-built ride app with fixed fares, advance booking, and in-app safety features. You can book at app.hopbahamas.com without downloading anything." },
      { q: "What is the best way to get around Nassau without Uber?", a: "HOP is the most direct Uber alternative in Nassau. It offers on-demand and pre-scheduled rides with fixed fares shown before you confirm. For short trips around downtown, Nassau's jitney buses cost $1.25–$3.50 and cover the main Bay Street corridor." },
      { q: "Can I pre-book a ride in Nassau before I arrive?", a: "Yes. HOP lets you schedule a pickup before you land. Enter your arrival time and pickup location and your driver will be confirmed and tracking your flight when you arrive — no waiting in a taxi queue after a long flight." },
      { q: "Are taxis in Nassau safe?", a: "Licensed Nassau taxis are generally safe. Look for yellow plates beginning with 'TN' — these are government-regulated. Always agree on the fare before you get in. HOP removes that step entirely with fixed prices and verified drivers." },
      { q: "Does HOP work without downloading an app?", a: "Yes. HOP's web app at app.hopbahamas.com works in any mobile browser with no download required. Useful when you land on roaming data and don't want to wait for an app install." },
      { q: "How much does it cost to get around Nassau?", a: "It depends on the option. Jitney buses cost $1.25–$3.50. Licensed taxis range from $15 for short port trips to $55 for airport-to-Atlantis. HOP offers fixed fares from $12 for short trips to $28 for the most popular airport routes." },
    ],
  },

  {
    slug: "nassau-taxi-cost-guide-2026",
    title: "Nassau Bahamas Taxi Fares 2026 — The Official Prices (No Surprises)",
    excerpt: "Government-regulated taxi fares for every major Nassau route — airport, cruise port, Atlantis, Baha Mar, Cable Beach. Plus how to avoid the overcharge.",
    category: "Nassau Travel Guide",
    date: "May 3, 2026",
    readTime: "4 min read",
    featured: false,
    metaTitle: "Nassau Bahamas Taxi Fares 2026 — Official Cost Guide | HOP",
    metaDescription: "Official Nassau taxi fare guide 2026. Airport to Atlantis, cruise port to Cable Beach, all major routes with prices. Plus how to avoid being overcharged.",
    targetKeyword: "nassau bahamas taxi cost",
    coverImage: "/images/dest-airport.jpg",
    content: [
      { type: "p", text: "Nassau taxi fares are set by the Bahamian government. The catch: they're not posted anywhere obvious, which means some drivers charge more than the official rate — not because they're bad people, but because tourists don't know what to expect. This guide gives you the full table so you do." },
      { type: "h2", text: "The Basics: How Nassau Taxi Pricing Works" },
      { type: "ul", items: [
        "Base rate: Set per zone, not by meter — Nassau taxis have no meters",
        "Extra passengers: +$3 per person beyond the first two",
        "Night surcharge (midnight–6am): approximately 25% added",
        "Luggage: Generally included. Ask before you load bags if you have a lot.",
        "Paradise Island bridge toll: $1 each way, added to all trips crossing to PI",
      ]},
      { type: "note", text: "Always agree on the fare before you get in. That's the single rule that prevents every dispute. 'How much to Atlantis?' — ask it before the door closes." },
      { type: "h2", text: "Nassau Airport (LPIA) Taxi Fares — 2026" },
      { type: "price-table", headers: ["Destination", "1–2 Passengers", "Each Extra Passenger"], rows: [
        ["Atlantis Paradise Island", "$45–$55", "+$3"],
        ["Baha Mar / Cable Beach", "$30–$36", "+$3"],
        ["Downtown Nassau / Bay Street", "$32–$40", "+$3"],
        ["Sandals Royal Bahamian", "$30–$36", "+$3"],
        ["Nassau Cruise Port", "$36–$42", "+$3"],
      ]},
      { type: "h2", text: "Nassau Cruise Port Taxi Fares — 2026" },
      { type: "price-table", headers: ["Destination", "1–2 Passengers", "Notes"], rows: [
        ["Atlantis Paradise Island", "$15–$20", "Includes $1 bridge toll"],
        ["Cable Beach", "$18–$24", ""],
        ["Baha Mar Resort", "$18–$24", ""],
        ["Sandals Royal Bahamian", "$18–$22", ""],
        ["Blue Lagoon Ferry Terminal", "$12–$16", "Take the ferry from there"],
        ["Nassau Airport (LPIA)", "$36–$42", "For day-of departures"],
      ]},
      { type: "h2", text: "How to Avoid Paying Too Much" },
      { type: "ul", items: [
        "Ask the price before you get in — this is non-negotiable",
        "Use this fare table as your benchmark",
        "If the driver won't quote upfront, walk to the next taxi",
        "At the cruise port, use the official taxi stand — avoid drivers who approach you off the queue",
        "Groups of 4+ should ask about a group rate — often cheaper per person than splitting into two taxis",
      ]},
      { type: "h2", text: "Skip the Whole Negotiation with HOP" },
      { type: "p", text: "HOP shows you the exact price before you confirm — not an estimate, the actual fare. Typically competitive with or below official taxi rates, and the negotiation is replaced by a tap. If the idea of asking a stranger 'how much to Atlantis' after a red-eye flight sounds exhausting, there's your answer." },
      { type: "related", posts: [
        { title: "No Uber in Nassau — Here's What Tourists Actually Use in 2026", slug: "no-uber-nassau-bahamas" },
        { title: "Why Pre-Scheduling Your Nassau Airport Transfer Is Always the Right Call", slug: "scheduled-rides-nassau-airport-transfer" },
      ]},
      { type: "cta", text: "See My Fixed Fare Now", href: "https://app.hopbahamas.com", subtext: "No download needed. Free cancellation." },
    ],
    faq: [
      { q: "How much does a taxi cost from Nassau airport to Atlantis?", a: "A licensed taxi from Lynden Pindling International Airport (LPIA) to Atlantis Paradise Island costs $45–$55 for 1–2 passengers, plus $3 per additional passenger. The Atlantis official shuttle costs $38 per adult. HOP offers a pre-bookable fixed fare from $28 — the cheapest option for most groups." },
      { q: "What is the fare from Nassau cruise port to Cable Beach?", a: "A taxi from Nassau Cruise Port (Prince George Wharf) to Cable Beach or Baha Mar costs approximately $18–$24 for 1–2 passengers. The journey takes 15–20 minutes." },
      { q: "Are Nassau taxis metered?", a: "No. Nassau taxis do not use meters. All fares are fixed zone rates set by the Bahamian government. Always agree on the price before entering any taxi — the absence of a meter means the fare is entirely negotiated." },
      { q: "Is there a cheaper option than a taxi from Nassau airport?", a: "Yes. HOP offers fixed fares typically 20–40% below the standard taxi rate for airport routes. A pre-bookable HOP ride from LPIA to Atlantis starts from $28, compared to $45–$55 by taxi or $38/person on the Atlantis shuttle." },
      { q: "Do you tip taxi drivers in Nassau, Bahamas?", a: "Tipping isn't mandatory but is appreciated — 10–15% is standard for tourists if the driver was helpful or assisted with luggage. HOP fares are all-inclusive with no tip expected." },
      { q: "Why do Nassau taxis have no meters?", a: "Nassau uses a zone-based fare system set by the Road Traffic Department rather than metered rates. This is common in smaller Caribbean markets. The downside for tourists is that fares must be agreed in advance — but the upside is prices are technically regulated, not dynamic." },
    ],
  },

  {
    slug: "nassau-airport-to-atlantis-transfer",
    title: "Nassau Airport to Atlantis: Every Transfer Option Compared (2026 Prices)",
    excerpt: "Official shuttle vs. taxi vs. HOP — priced out for the most common Nassau airport transfer. Know your number before you land.",
    category: "Nassau Travel Guide",
    date: "April 28, 2026",
    readTime: "4 min read",
    featured: false,
    metaTitle: "Nassau Airport to Atlantis Transfer 2026 — All Options Compared | HOP",
    metaDescription: "Nassau Airport to Atlantis transfer comparison: official shuttle, taxis, and HOP. Prices, journey times, and what to book in advance. Updated 2026.",
    targetKeyword: "nassau airport to atlantis transfer",
    coverImage: "/images/dest-atlantis.jpg",
    content: [
      { type: "p", text: "The drive from Nassau's Lynden Pindling International Airport to Atlantis Paradise Island is 9.5 miles and takes 25–35 minutes. It's also one of the most expensive short drives in the Caribbean if you don't know what you're doing. Here's every option, what it costs, and what's actually worth it." },
      { type: "h2", text: "All Your Options Side-by-Side" },
      { type: "price-table", headers: ["Option", "Price (2 passengers)", "Journey Time", "Pre-Bookable?", "Best For"], rows: [
        ["Atlantis Official Shuttle", "$38/person ($76 total)", "25–35 min", "Yes, through Atlantis", "Guests who want it handled"],
        ["Licensed Nassau Taxi", "$45–$55", "25–35 min", "No", "Cash-preferred travelers"],
        ["HOP App", "from $28 fixed", "25–35 min", "Yes, before you land", "Most travelers"],
        ["Rental Car", "$60–$90/day + toll", "25–35 min", "Yes", "Stays of 4+ days"],
      ]},
      { type: "h2", text: "Option 1: The Atlantis Official Shuttle ($38/person)" },
      { type: "p", text: "Atlantis runs their own shuttle from LPIA in Mercedes-Benz vehicles. It's comfortable, reliable, and professionally run. It's also $38 per adult, which means a family of four pays $152 one way — $304 for the round trip. The shuttle runs on schedule, not on demand, so you might wait. There's nothing wrong with it, it's just expensive for what it is." },
      { type: "h2", text: "Option 2: Licensed Nassau Taxi ($45–$55)" },
      { type: "p", text: "Yellow taxis with TN plates queue at the arrivals hall. The government rate to Atlantis is $45–$55 for 1–2 passengers, plus $3 per additional person and a $1 Paradise Island bridge toll. The problem isn't safety — licensed Nassau taxis are generally fine. The problem is there's no posted price, no app to compare, and after a long flight you're now negotiating with someone who does this every day. Experience advantage: not yours." },
      { type: "h2", text: "Option 3: HOP (Recommended for Most Travelers)" },
      { type: "p", text: "HOP is a Nassau-native ride app. The fare to Atlantis starts from $28, it's shown before you confirm, and you can book it before your plane even takes off. Your driver tracks your flight and meets you at arrivals — no taxi stand, no negotiation, no 'how much did you say?' after you've already loaded the bags." },
      { type: "ul", items: [
        "Fixed fare from $28 — shown before you commit, never changes",
        "Book before your flight — driver confirmed when you land",
        "Works in any browser — no download needed at the airport",
        "Real-time tracking and SOS safety built in",
        "Group vehicles available for families",
      ]},
      { type: "h2", text: "The Math for a Family of Four" },
      { type: "p", text: "Atlantis shuttle: $38 × 4 = $152 each way. Licensed taxi with 4 passengers: $55 + $6 (extra passengers) = $61. HOP for 4: fixed fare from $28 regardless of passenger count. For a 7-night stay with two airport transfers, that's $224 saved versus the official shuttle — enough for a few rounds at Nobu. You're welcome." },
      { type: "related", posts: [
        { title: "Nassau Bahamas Taxi Fares 2026 — The Official Prices (No Surprises)", slug: "nassau-taxi-cost-guide-2026" },
        { title: "Why Pre-Scheduling Your Nassau Airport Transfer Is Always the Right Call", slug: "scheduled-rides-nassau-airport-transfer" },
      ]},
      { type: "cta", text: "Book My Nassau Airport Transfer", href: "https://app.hopbahamas.com", subtext: "Fixed fare from $28 to Atlantis. Free cancellation. No download needed." },
    ],
    faq: [
      { q: "How much is the transfer from Nassau airport to Atlantis?", a: "The Atlantis official shuttle is $38 per adult. Licensed taxis are $45–$55 for 1–2 passengers. HOP offers pre-bookable fixed fares from $28 — the same journey, lower price, bookable before you land." },
      { q: "How far is Atlantis from Nassau airport?", a: "Atlantis Paradise Island is approximately 9.5 miles (15 km) from Lynden Pindling International Airport. The drive takes 25–35 minutes by road, including the Paradise Island bridge." },
      { q: "Can I book an airport transfer to Atlantis in advance?", a: "Yes. HOP allows advance booking — enter your flight number and your driver will be confirmed and at arrivals when you land. The Atlantis shuttle can also be pre-booked directly through Atlantis reservations." },
      { q: "How long does the drive from Nassau airport to Atlantis take?", a: "25–35 minutes under normal conditions. Heavier traffic during weekday morning rush (7–9am) and around cruise ship arrivals. HOP displays a live ETA when you book." },
      { q: "Is the Atlantis hotel shuttle worth the price?", a: "The Atlantis shuttle is reliable but expensive at $38 per adult. For solo travelers, the premium for a hassle-free Atlantis-branded experience may be worth it. For couples or families, a pre-booked HOP ride is significantly cheaper for the same journey time." },
      { q: "What is the cheapest way from Nassau airport to Atlantis?", a: "HOP is the cheapest pre-bookable option at fixed fares from $28 for the full vehicle — not per person. For 2+ passengers it undercuts both the taxi rate and the official Atlantis shuttle." },
    ],
  },

  {
    slug: "nassau-cruise-port-transportation-guide",
    title: "Nassau Cruise Port Transportation 2026 — Every Option With Real Prices",
    excerpt: "Your ship just docked at Prince George Wharf. Here's exactly how to get anywhere — Atlantis, Cable Beach, Blue Lagoon — with prices and the pre-booking trick most cruise passengers miss.",
    category: "Nassau Travel Guide",
    date: "April 22, 2026",
    readTime: "6 min read",
    featured: false,
    metaTitle: "Nassau Cruise Port Transportation 2026 — Complete Guide | HOP",
    metaDescription: "Every transport option from Nassau Cruise Port to Atlantis, Cable Beach, Blue Lagoon, and downtown — with prices, times, and pre-booking. Updated 2026.",
    targetKeyword: "nassau cruise port transportation",
    coverImage: "/images/dest-cruise.jpg",
    content: [
      { type: "p", text: "Your cruise ship docked at Prince George Wharf. You have somewhere between 6 and 10 hours. Downtown Nassau is literally a 5-minute walk. Atlantis and Cable Beach are 15–20 minutes away. Here's everything you need to know so you spend those hours actually doing things instead of standing at a taxi stand wondering what to pay." },
      { type: "h2", text: "What's Walking Distance?" },
      { type: "ul", items: [
        "Downtown Nassau / Bay Street: 5-minute walk. Markets, restaurants, Bahamian food.",
        "Junkanoo Beach: 10-minute walk west along the waterfront. Free public beach.",
        "Fort Charlotte: 15-minute walk or short ride. Historic fort, great views, free entry.",
        "Straw Market: Right outside the port exit. Crafts, souvenirs, local goods.",
      ]},
      { type: "h2", text: "Taxi Fares from Nassau Cruise Port" },
      { type: "price-table", headers: ["Destination", "Taxi (1–2 pax)", "HOP Fixed Fare", "Journey Time"], rows: [
        ["Atlantis Paradise Island", "$15–$20", "from $15", "10–20 min"],
        ["Cable Beach / Baha Mar", "$18–$24", "from $18", "15–20 min"],
        ["Sandals Royal Bahamian", "$18–$22", "from $18", "15 min"],
        ["Blue Lagoon Ferry Terminal", "$12–$16", "from $12", "10 min (+ 25 min ferry)"],
        ["Nassau Airport (LPIA)", "$36–$42", "from $32", "25–35 min"],
      ]},
      { type: "note", text: "Use the official taxi stand at Prince George Wharf — it's clearly marked near the exit. Drivers who approach you off the queue aren't necessarily dangerous, but the stand is regulated and easier to compare prices." },
      { type: "h2", text: "Nassau's $1.25 Secret: The Jitney Bus" },
      { type: "p", text: "The jitney is Nassau's public minibus system and it costs $1.25–$3.50. Route 10 runs east–west along Bay Street and connects the port to Cable Beach. It's not scheduled (you flag it down), it gets packed during peak hours, and it's not ideal with a day bag — but for a solo traveler who wants to see how Nassau actually moves, it's the best $2.50 you'll spend on the island." },
      { type: "h2", text: "Pre-Book Your Transfer Before the Ship Docks" },
      { type: "p", text: "Most cruise passengers don't know this is possible: you can pre-book a Nassau pickup through HOP before your voyage and have a driver confirmed for the exact time your ship arrives. Walk off the gangway and into a confirmed ride, not into a negotiation with 400 other cruise passengers doing the same thing." },
      { type: "p", text: "This matters most when you're heading somewhere time-sensitive — like Blue Lagoon Island (ferries run on schedule) or an Atlantis day pass (which has entry cutoff times)." },
      { type: "h2", text: "Getting Back Before Your Ship Leaves" },
      { type: "p", text: "Build in a 45-minute buffer before departure. Nassau traffic can stack when multiple ships dock the same morning — sometimes 5–7 cruise ships arrive simultaneously. If your ship departs at 4:30pm, aim for the port by 3:45pm. HOP lets you schedule your return ride in advance so you're not hunting for a taxi when every other cruise passenger is doing the same." },
      { type: "related", posts: [
        { title: "Group Transportation in Nassau Bahamas — What to Book and When", slug: "group-travel-bahamas-mini-bus" },
        { title: "How to Get Around Nassau Bahamas in 2026 — Every Option Explained", slug: "how-to-get-around-nassau-bahamas" },
      ]},
      { type: "cta", text: "Pre-Book My Cruise Port Transfer", href: "https://app.hopbahamas.com", subtext: "Schedule your pickup before your ship docks. Fixed price, no negotiation." },
    ],
    faq: [
      { q: "How do I get from Nassau cruise port to Atlantis?", a: "Atlantis Paradise Island is 3.5 miles from Prince George Wharf. A taxi costs $15–$20 for 1–2 passengers and takes 10–20 minutes. You can pre-book a HOP ride from $15 to have a confirmed driver waiting when you dock." },
      { q: "How long can I spend in Nassau on a cruise?", a: "Most Nassau cruise stops run 6–10 hours. Atlantis is 15 minutes from port. Blue Lagoon Island needs a taxi plus a 25-minute ferry. Plan to be back at the ship 45 minutes before your departure time." },
      { q: "Is there a free beach near Nassau cruise port?", a: "Yes. Junkanoo Beach is a 10-minute walk west of Prince George Wharf — free public access, food and drink vendors on site, water sports rentals available." },
      { q: "Can I pre-book transportation from Nassau cruise port?", a: "Yes. HOP lets cruise passengers schedule pickups before they even board their ship. Book in advance and your driver will meet you at the terminal when you dock." },
      { q: "How much is a taxi from Nassau cruise port to Cable Beach?", a: "A taxi from Nassau Cruise Port to Cable Beach or Baha Mar costs approximately $18–$24 for 1–2 passengers. The drive takes 15–20 minutes." },
      { q: "Is the Nassau taxi stand at the cruise port safe?", a: "Yes. The official taxi stand at Prince George Wharf is government-regulated and clearly marked at the port exit. Licensed drivers have TN-prefix yellow plates and government-issued ID. Use the stand rather than accepting offers from drivers who approach you off-queue." },
    ],
  },

  {
    slug: "how-to-get-around-nassau-bahamas",
    title: "How to Get Around Nassau Bahamas in 2026 — Every Option Explained",
    excerpt: "Taxis, jitneys, rental cars, HOP app — every way to get around Nassau with honest prices, honest advice, and no sales pitch.",
    category: "Nassau Travel Guide",
    date: "April 15, 2026",
    readTime: "7 min read",
    featured: false,
    metaTitle: "How to Get Around Nassau Bahamas 2026 — Complete Transport Guide | HOP",
    metaDescription: "Complete guide to getting around Nassau, Bahamas in 2026. Taxis, jitneys, rental cars, HOP app — every option explained with real prices for tourists and cruise passengers.",
    targetKeyword: "how to get around nassau bahamas",
    coverImage: "/images/dest-nassau.jpg",
    content: [
      { type: "p", text: "Getting around Nassau is easy once you know the system. The problem is most tourists don't find out the system until after they've overpaid for a taxi or waited 40 minutes for something that never showed up. Here's the full picture before you land." },
      { type: "h2", text: "All Nassau Transportation Options at a Glance" },
      { type: "price-table", headers: ["Option", "Cost", "Best For", "Skip If..."], rows: [
        ["Walking", "Free", "Downtown Nassau, Bay Street, Junkanoo Beach", "It's over 88°F. Every day."],
        ["Jitney Bus", "$1.25–$3.50", "Budget travelers, Bay Street corridor", "You have luggage or a schedule"],
        ["Licensed Taxi", "$12–$55+", "Direct routes, groups up to 4", "You hate negotiating prices"],
        ["HOP App", "from $12 fixed", "Fixed fares, pre-booking, safety features", "You only need something once"],
        ["Rental Car", "$60–$90/day", "Multi-day stays, full island exploration", "You're staying 3 nights or fewer"],
        ["Resort Shuttle", "$38–$45/person", "Atlantis/Baha Mar guests who want hassle-free", "You have 2+ people in your group"],
      ]},
      { type: "h2", text: "Walking: Great for Downtown, That's It" },
      { type: "p", text: "Nassau's waterfront from the cruise port along Bay Street to the British Colonial Hotel is genuinely walkable. Junkanoo Beach is 10 minutes west on foot. The Straw Market is right at the port. But Nassau runs hot — and the resort areas (Atlantis, Baha Mar, Cable Beach) are 3–10 miles from downtown. Walking gets you around Rawson Square. It doesn't get you to the beach that's in every photo." },
      { type: "h2", text: "Jitney Buses: Nassau's Best-Kept Budget Secret" },
      { type: "p", text: "Nassau's public minibuses are called jitneys. $1.25–$3.50 per trip. Route 10 is the one tourists use — it runs east–west along Bay Street. You flag them down on the road; they run informal schedules. No AC on older vehicles, no luggage space, unpredictable timing. But for a solo traveler willing to roll with it, jitneys are how Nassau locals actually move — and that experience costs $2." },
      { type: "h2", text: "Licensed Taxis: Reliable but Unmetered" },
      { type: "p", text: "Nassau's licensed taxis are yellow-plated with 'TN' prefixes. Government-regulated, generally professional, no surprises on the safety side. The one thing to know: no meters. Every fare is quoted upfront by the driver. Government guidelines exist but aren't always followed. Ask the fare before you sit down — that's the rule that keeps everything straightforward." },
      { type: "note", text: "Official Nassau taxi rate: LPIA airport to Atlantis is $45–$55. If someone quotes significantly more, politely move on." },
      { type: "h2", text: "HOP: The Uber Equivalent Built for Nassau" },
      { type: "p", text: "HOP is the app-based answer to Nassau's taxi system. You see the price before you confirm (no negotiation), you can pre-book before you arrive, and it works on Nassau's sometimes-spotty mobile data. For tourists used to Uber or Lyft, it's the same experience — minus the surge pricing, plus the island." },
      { type: "ul", items: [
        "Book via web app — no download needed",
        "Fixed fares from $12 for short hops",
        "Schedule pickups before your flight or cruise ship arrives",
        "Low Data Mode — works on weak Nassau signal",
        "SOS safety — one tap, emergency services and trusted contacts notified",
        "Group vehicles — standard, SUV, and Mini Bus (up to 15 passengers)",
      ]},
      { type: "h2", text: "Rental Cars: Only Worth It for Longer Stays" },
      { type: "p", text: "Rental cars in Nassau run $60–$90/day plus insurance. Nassau drives on the left side of the road (British-style). Roads are manageable, but parking near Atlantis and downtown is limited. For a cruise day-tripper or a 2-night hotel stay, the math rarely works. For a 5-day vacation where you want to explore New Providence beyond the resort corridor, a rental car earns its keep." },
      { type: "h2", text: "What We'd Recommend by Visitor Type" },
      { type: "price-table", headers: ["Visitor Type", "Best Option", "Why"], rows: [
        ["Cruise Passenger (Day Trip)", "Pre-book HOP + jitney for downtown", "Fixed time window, reliability matters"],
        ["Resort Guest at Atlantis/Baha Mar", "HOP for off-resort trips", "Resort shuttles charge per person"],
        ["Airport Arrival", "Pre-booked HOP", "No negotiation after a long flight"],
        ["Solo Budget Traveler", "Jitney + HOP when needed", "Mix cheap daily transit with on-demand"],
        ["Family of 4+", "HOP group vehicle", "Cheaper per person than two taxis"],
        ["Week-long Stay", "HOP first few days, rental car after", "Rental pays off once you want to explore"],
      ]},
      { type: "related", posts: [
        { title: "No Uber in Nassau — Here's What Tourists Actually Use in 2026", slug: "no-uber-nassau-bahamas" },
        { title: "Nassau Cruise Port Transportation 2026 — Every Option With Real Prices", slug: "nassau-cruise-port-transportation-guide" },
      ]},
      { type: "cta", text: "Book My Nassau Ride", href: "https://app.hopbahamas.com", subtext: "Fixed fares. No download needed. Pre-book before you land." },
    ],
    faq: [
      { q: "What is the best way to get around Nassau, Bahamas?", a: "For most tourists, HOP is the easiest all-around option — fixed fares, advance booking, and it works like the Uber you're used to. For budget travelers exploring the Bay Street area, jitneys at $1.25 are hard to beat. Rental cars only make sense for stays of 4+ days." },
      { q: "Is there public transportation in Nassau, Bahamas?", a: "Yes. Nassau's public minibus system (jitneys) runs routes across the island for $1.25–$3.50 per trip. Route 10 covers Bay Street and connects the cruise port to Cable Beach. Jitneys don't follow printed schedules — you flag them down on the road." },
      { q: "How much does transportation cost in Nassau?", a: "Jitneys: $1.25–$3.50. Taxis: $12 for short hops up to $55 for airport-to-Atlantis. HOP: fixed fares from $12 depending on route. Resort shuttles: $38–$45 per person per trip. Walking: free, but only useful downtown." },
      { q: "Can I use Uber or Lyft in Nassau, Bahamas?", a: "No. Neither Uber nor Lyft operates in Nassau. The local equivalent is HOP — a Nassau-built ride app with fixed fares and advance booking. Use it at app.hopbahamas.com." },
      { q: "Is it safe to walk around Nassau?", a: "Downtown Nassau along Bay Street and the waterfront is generally safe for tourists during the day. The cruise port area, Rawson Square, and the British Colonial stretch are busy and well-traveled. For evening transport or trips outside the downtown core, use HOP or a licensed taxi." },
      { q: "Do I need to rent a car in Nassau?", a: "For most stays of 3 nights or fewer, no. HOP and taxis cover every tourist destination. For 5+ day stays where you want to explore eastern New Providence beyond the resort corridor, a rental car starts to make economic sense." },
    ],
  },

  {
    slug: "nassau-taxi-safe-tourist-guide",
    title: "Are Taxis in Nassau, Bahamas Safe? What Tourists Actually Need to Know",
    excerpt: "Short answer: yes — if you use licensed ones. Here's how to spot them, what to watch out for, and why HOP eliminates every concern on the list.",
    category: "Nassau Travel Guide",
    date: "April 8, 2026",
    readTime: "4 min read",
    featured: false,
    metaTitle: "Are Nassau Bahamas Taxis Safe? (2026 Honest Guide) | HOP",
    metaDescription: "Honest guide to taxi safety in Nassau, Bahamas. How to identify licensed taxis, what scams exist, and what HOP offers as the verified alternative. 2026.",
    targetKeyword: "nassau bahamas taxi safe",
    coverImage: "/images/dest-nassau.jpg",
    content: [
      { type: "p", text: "Licensed taxis in Nassau are generally safe. The majority of Nassau taxi drivers are experienced professionals who've been serving tourists for years. That said, 'generally' is doing a lot of work in that sentence — so here's what specifically to look for, and what to skip entirely." },
      { type: "h2", text: "How to Spot a Licensed Nassau Taxi" },
      { type: "ul", items: [
        "Yellow license plates starting with 'TN' — this is the government-licensing indicator",
        "Blue and yellow government registration stickers visible inside the vehicle",
        "At airports and the cruise port, licensed taxis queue at designated taxi stands",
        "Licensed drivers carry photo ID cards and are required to show them on request",
        "Most are minivans or full-size sedans in reasonable condition",
      ]},
      { type: "h2", text: "Three Real Concerns (and What to Do About Them)" },
      { type: "h3", text: "No meters — and prices aren't posted" },
      { type: "p", text: "This is the main issue. Nassau taxis have no meters. Fares are government-regulated but aren't displayed anywhere in the vehicle. The fix is simple: ask 'how much to [destination]?' before you get in. Airport to Atlantis should be $45–$55. Cruise port to Cable Beach should be $18–$24. If the quote is way above those, you can walk to the next taxi without drama." },
      { type: "h3", text: "Drivers who approach you off the official queue" },
      { type: "p", text: "At Nassau Cruise Port, unofficial drivers sometimes approach tourists near the gangway exit. These aren't necessarily unsafe — but they're unregulated. The official taxi stand is clearly marked at Prince George Wharf. Using it means regulated drivers and prices that are easier to dispute if needed." },
      { type: "h3", text: "Solo travel and late-night transport" },
      { type: "p", text: "For solo travelers or late-night trips, the verification that a street taxi can't provide matters. You don't know the driver's name, you have no record of the vehicle, and there's no one tracking the route. That's where a ride app fills a real gap." },
      { type: "h2", text: "What HOP Provides That Taxis Don't" },
      { type: "p", text: "HOP isn't pitching you safety theater — these are actual features that address the real concerns above:" },
      { type: "ul", items: [
        "All drivers background-checked and verified before they drive on the platform",
        "Driver name, photo, and license plate shown before the ride starts — not after",
        "Fixed fare confirmed before you commit — no negotiation at all",
        "Real-time GPS tracking, shareable with anyone you choose",
        "SOS button connects to Nassau 919 and alerts your trusted contacts instantly",
        "HOP Safety Desk monitors rides and can dispatch assistance if something goes wrong",
      ]},
      { type: "note", text: "Trusted contacts receive a live tracking link for every ride you take — not just in emergencies. For solo travelers with someone back home keeping tabs, this is the feature that matters most." },
      { type: "h2", text: "The Honest Bottom Line" },
      { type: "p", text: "Nassau isn't dangerous for tourists. Licensed taxis are fine for most trips. But if price transparency, driver verification, and a genuine safety net matter to you — especially alone, at night, or with kids — HOP covers everything licensed taxis don't." },
      { type: "cta", text: "Book a Verified Nassau Ride", href: "https://app.hopbahamas.com", subtext: "Driver name, photo, and plate shown before every ride." },
    ],
    faq: [
      { q: "Is it safe to take a taxi in Nassau, Bahamas?", a: "Yes, licensed Nassau taxis are generally safe. Use taxis with yellow TN plates from official taxi stands at the airport and cruise port. Always agree on the fare before entering. For driver verification and live tracking, HOP provides those features on every ride." },
      { q: "How do I know if a Nassau taxi is licensed?", a: "Licensed Nassau taxis have yellow license plates beginning with 'TN' and blue-and-yellow government registration stickers inside the vehicle. At the airport and cruise port, use the designated taxi stands rather than accepting offers from drivers who approach you." },
      { q: "Is Nassau safe for solo female travelers?", a: "Nassau's tourist areas are generally safe for solo female travelers during the day. For ground transport, HOP provides name, photo, and plate number before the ride starts, plus real-time GPS tracking shared with contacts and a one-tap SOS. Those aren't marketing points — they're practical tools for traveling alone." },
      { q: "What do I do if a Nassau taxi overcharges me?", a: "If a driver charges significantly above the regulated rate, you can report it to the Nassau Taxi Cab Union or the Bahamas Tourist Board. The fix is prevention: agree on the fare before you get in. If you used HOP, the fare is fixed in the app and not subject to adjustment." },
      { q: "Does Nassau have a ride app with driver tracking?", a: "Yes. HOP shows your driver's name, photo, and vehicle plate before your ride begins. It also includes live GPS tracking and a one-tap SOS button connected to Nassau 919 emergency services." },
      { q: "Are Nassau taxis safe at night?", a: "Licensed taxis are generally fine at night in Nassau's tourist areas. For late-night transport, pre-booking with HOP adds driver verification and tracking that street hailing doesn't — useful whether you're safety-conscious by nature or just practical about it." },
    ],
  },

  {
    slug: "how-to-get-from-nassau-airport-to-atlantis",
    title: "Nassau Airport to Atlantis Paradise Island — Fastest Way to Get There",
    excerpt: "The most common Nassau transfer, priced out simply. Here's the fastest way to book it with a confirmed price before you land.",
    category: "Nassau Travel Guide",
    date: "April 20, 2026",
    readTime: "4 min read",
    featured: false,
    metaTitle: "Nassau Airport to Atlantis Transfer Guide | HOP",
    metaDescription: "How to get from Nassau Airport (LPIA) to Atlantis Paradise Island. Fixed fare transfers, taxis, and the official shuttle — compared with 2026 prices.",
    targetKeyword: "nassau airport atlantis",
    content: [
      { type: "p", text: "Lynden Pindling International Airport is 9.5 miles from Atlantis Paradise Island — about 25–35 minutes by road. It's the most common transfer in Nassau, and also the one where not knowing your options costs the most money." },
      { type: "p", text: "Three options worth knowing: the Atlantis official shuttle ($38/person), a licensed Nassau taxi ($45–$55 for 1–2 passengers), and a pre-booked HOP ride (from $28, fixed price, confirmed before your plane lands). The journey time is the same on all three." },
      { type: "h2", text: "Why Pre-Booking Is Worth It" },
      { type: "p", text: "Booking before your flight departs means you walk out of Nassau arrivals directly into your confirmed ride. No taxi queue. No comparing quotes with someone who's more rested than you after a red-eye. Your driver has already been tracking your flight." },
      { type: "cta", text: "Book My Airport Transfer", href: "https://app.hopbahamas.com", subtext: "Fixed fare from $28. Book before you land." },
    ],
    faq: [
      { q: "How much is the transfer from Nassau airport to Atlantis?", a: "The Atlantis official shuttle is $38 per adult. Licensed taxis charge $45–$55 for 1–2 passengers. HOP offers pre-bookable fixed fares from $28 — the lowest price for the same journey time." },
      { q: "Can I pre-book a Nassau airport pickup before I arrive?", a: "Yes. HOP's scheduling feature lets you book before you travel. Enter your flight number and arrival time and your driver will be confirmed and waiting when you clear customs." },
      { q: "How long is the drive from Nassau airport to Atlantis?", a: "25–35 minutes under normal traffic. Slightly longer during weekday morning rush (7–9am) and when multiple cruise ships are in port simultaneously." },
    ],
  },

  {
    slug: "scheduled-rides-nassau-airport-transfer",
    title: "Why Pre-Scheduling Your Nassau Airport Transfer Is Always the Right Call",
    excerpt: "Early morning arrivals, holiday weekends, cruise schedule overlaps — Nassau taxi availability can be unpredictable. Here's why booking 24 hours ahead is always the smarter move.",
    category: "Tips",
    date: "April 15, 2026",
    readTime: "3 min read",
    featured: false,
    metaTitle: "Pre-Schedule Your Nassau Airport Transfer | HOP",
    metaDescription: "Why scheduling your Nassau airport transfer in advance beats showing up and hoping. Fixed price, guaranteed pickup, no airport taxi queue stress.",
    targetKeyword: "nassau airport transfer pre-book",
    content: [
      { type: "p", text: "Nassau's Lynden Pindling International Airport processes flights from the US, Canada, Europe, and regional Caribbean connections. On any given morning, multiple international flights arrive within the same 45-minute window. Taxi availability at arrivals is not guaranteed — especially on long weekends and during peak season." },
      { type: "p", text: "Pre-scheduling your airport transfer with HOP means your driver is confirmed before your flight takes off, your fare is locked, and your first moments in the Bahamas aren't spent on a negotiation. That's the whole pitch. It's a good one." },
      { type: "h2", text: "How Scheduling Works on HOP" },
      { type: "ul", items: [
        "Open the HOP app or web app before your flight departs",
        "Enter your arrival airport (LPIA) and your destination",
        "Select scheduled ride and enter your flight number or arrival time",
        "Confirm your fixed fare — no changes when you land",
        "Your driver is notified and tracks your flight in real time",
      ]},
      { type: "cta", text: "Schedule My Nassau Airport Pickup", href: "https://app.hopbahamas.com", subtext: "Lock in your fare before you land." },
    ],
    faq: [
      { q: "Can I book a Nassau airport pickup before I travel?", a: "Yes. HOP's scheduling feature lets you book days or weeks in advance. Enter your flight number and arrival time and your driver will be confirmed and waiting when you arrive." },
      { q: "What if my flight is delayed?", a: "HOP drivers monitor your flight status in real time. If your flight is delayed, your driver adjusts accordingly — no cancellation, no rebooking, no extra charge." },
    ],
  },

  {
    slug: "group-travel-bahamas-mini-bus",
    title: "Group Transportation in Nassau Bahamas — What to Book and When",
    excerpt: "Groups of 5+ in Nassau end up paying more per person in taxis than they should. HOP's flat-rate Mini Bus seats 15. Here's how to plan group transport properly.",
    category: "Group Travel",
    date: "April 10, 2026",
    readTime: "5 min read",
    featured: false,
    metaTitle: "Group Transportation Nassau Bahamas | HOP Luxury Mini Bus",
    metaDescription: "Group transportation in Nassau Bahamas — HOP's Mini Bus holds up to 15 passengers at flat rates. Perfect for cruise groups, family trips, and resort transfers.",
    targetKeyword: "nassau group transportation",
    content: [
      { type: "p", text: "Groups in Nassau have a math problem. Two licensed taxis for 6 people costs $90–$110 from the airport to Atlantis. One HOP group vehicle costs $28 flat for the same trip — same road, same traffic, significantly different bill. Here's how to book it right." },
      { type: "h2", text: "HOP Group Vehicle Options" },
      { type: "price-table", headers: ["Vehicle", "Capacity", "Flat Rate"], rows: [
        ["Standard", "1–4 passengers", "From $15"],
        ["Luxury Sedan", "Up to 4 passengers", "$95 flat, anywhere in Nassau"],
        ["Luxury SUV", "Up to 7 passengers", "$120 flat, anywhere in Nassau"],
        ["Luxury Mini Bus", "Up to 15 passengers", "$190 flat, anywhere in Nassau"],
      ]},
      { type: "p", text: "The Mini Bus at $190 for 15 people is $12.67 per head. That beats a jitney bus and it comes with a confirmed driver, air conditioning, and luggage space. For a family reunion, wedding group, or tour party, the math is embarrassingly obvious." },
      { type: "cta", text: "Book a Group Ride in Nassau", href: "https://app.hopbahamas.com", subtext: "All group sizes. Flat rates. Book before you arrive." },
    ],
    faq: [
      { q: "How do I book group transportation in Nassau?", a: "Book through the HOP app or web app and select your vehicle type based on group size. Standard up to 4, Luxury SUV up to 7, Mini Bus up to 15. For groups larger than 15, contact HOP directly for custom arrangements." },
      { q: "What is the cheapest way to transport a group in Nassau?", a: "HOP's Luxury Mini Bus at $190 flat for up to 15 passengers works out to under $13 per person — significantly cheaper than booking multiple taxis and still includes a verified driver, AC, and luggage space." },
    ],
  },

  {
    slug: "low-data-mode-explained",
    title: "HOP Low Data Mode — Why It Matters When Nassau's Signal Drops",
    excerpt: "Parts of Nassau and Paradise Island have unreliable mobile data, especially on roaming. HOP's Low Data Mode keeps the app working when signal gets patchy.",
    category: "Features",
    date: "April 5, 2026",
    readTime: "3 min read",
    featured: false,
    metaTitle: "HOP Low Data Mode — Works on Nassau's Weak Signal | HOP",
    metaDescription: "HOP's Low Data Mode keeps the ride app functional on Nassau's sometimes-unreliable mobile data. How it works and why it matters for tourists on roaming.",
    targetKeyword: "hop low data mode nassau",
    content: [
      { type: "p", text: "Nassau's mobile data coverage is uneven — noticeably so on parts of Paradise Island, eastern New Providence, and on roaming SIM cards that haven't fully connected to the local network. Most ride apps fail silently when signal drops. HOP doesn't — that's a deliberate design decision, not luck." },
      { type: "h2", text: "What Low Data Mode Actually Does" },
      { type: "ul", items: [
        "Pauses live map animation — which is the heaviest data consumer by far",
        "Keeps active ride tracking and ETA updating in real time — just without the map visuals",
        "Maintains in-app driver messaging so you can still communicate",
        "Reduces per-ride data consumption by approximately 70%",
      ]},
      { type: "p", text: "The practical result: your ride stays tracked, your driver stays connected, and you know your ETA — even on the kind of patchy roaming signal that makes every other app useless. The map goes static, but everything that matters keeps working." },
      { type: "cta", text: "Download HOP — Works Everywhere in Nassau", href: "https://app.hopbahamas.com", subtext: "Fixed fares. No download required. Works on weak Nassau signal." },
    ],
    faq: [
      { q: "What happens if I lose signal during a HOP ride?", a: "Low Data Mode activates automatically. The ride continues, GPS tracking stays live, and the driver remains on route. The map animation pauses but all functional features — tracking, ETA, messaging — keep running." },
    ],
  },

  {
    slug: "nassau-luxury-car-service-vs-hop",
    title: "Nassau Luxury Car Service vs. HOP Luxury — What's Actually Different?",
    excerpt: "Traditional Nassau luxury services mean phone calls, negotiated rates, and trust in someone you've never used. HOP Luxury is the same vehicle quality with transparent flat rates.",
    category: "Nassau Travel Guide",
    date: "March 28, 2026",
    readTime: "4 min read",
    featured: false,
    metaTitle: "Nassau Luxury Car Service vs HOP — Which Is Better? | HOP",
    metaDescription: "Compare Nassau luxury car services to HOP Luxury. Transparent flat rates, in-app booking, and verified professional drivers — no phone calls, no negotiation.",
    targetKeyword: "nassau luxury car service",
    content: [
      { type: "p", text: "Traditional luxury car services in Nassau do exist — black-car operators with premium vehicles and resort relationships. The experience: you find them through your hotel concierge or a Google search, call to arrange, negotiate a rate, and hope the car that shows up matches what you agreed to. HOP Luxury is the same class of vehicle with the negotiation replaced by a flat rate you see before you book." },
      { type: "price-table", headers: ["Feature", "Traditional Luxury Car", "HOP Luxury"], rows: [
        ["Booking method", "Phone call or hotel concierge", "In-app or web, 2 minutes"],
        ["Pricing", "Negotiated, varies", "Flat rate shown upfront"],
        ["Sedan", "~$100–$150", "$95 flat, anywhere in Nassau"],
        ["SUV", "~$130–$180", "$120 flat, anywhere in Nassau"],
        ["Mini Bus (up to 15)", "~$200–$300", "$190 flat, anywhere in Nassau"],
        ["Price transparency", "Ask and see", "Price confirmed before booking"],
      ]},
      { type: "p", text: "If you prefer the human touch of a concierge recommendation, traditional services deliver that. If you'd rather tap, confirm, and know exactly what you're paying before the car arrives — that's HOP Luxury." },
      { type: "cta", text: "Book HOP Luxury in Nassau", href: "https://app.hopbahamas.com", subtext: "Flat-rate luxury. No calls, no negotiation." },
    ],
    faq: [
      { q: "How much does a luxury car service cost in Nassau Bahamas?", a: "Traditional Nassau luxury services typically charge $100–$180 depending on vehicle type and route. HOP Luxury offers transparent flat rates: Sedan $95, SUV $120, Mini Bus $190 — all-inclusive, anywhere in Nassau, booked in-app without a phone call." },
    ],
  },

  {
    slug: "hop-moments-rewards-guide",
    title: "HOP Moments: How to Earn Rewards on Every Nassau Trip",
    excerpt: "Share photos and videos from Nassau and earn points toward ride credits. Here's exactly how the points system works and the fastest path to your first reward.",
    category: "Features",
    date: "March 22, 2026",
    readTime: "3 min read",
    featured: false,
    metaTitle: "HOP Moments Rewards Guide — Earn Points on Every Nassau Ride | HOP",
    metaDescription: "Complete guide to earning HOP Moments points in Nassau. Share photos and videos from your trip to earn ride credits and exclusive rewards.",
    targetKeyword: "hop moments rewards",
    content: [
      { type: "p", text: "HOP Moments is simple: share content from Nassau through the app, earn points, redeem for ride credits. It's the kind of feature that actually makes sense for a tourist destination — you're already taking photos. You might as well get something back for them." },
      { type: "price-table", headers: ["Content Type", "Points Earned"], rows: [
        ["Photo", "50 points"],
        ["Video", "100 points"],
        ["Reel / Short video", "195 points"],
      ]},
      { type: "h2", text: "Reward Milestones" },
      { type: "ul", items: [
        "250 points — First reward tier unlocked",
        "500 points — Second tier",
        "750 points — Third tier",
        "1,000 points — Top tier reward",
      ]},
      { type: "p", text: "One reel gets you 195 points. Three photos gets you 150. Posting consistently across a week in Nassau gets you to the first milestone without trying. The rewards apply to future HOP rides — which is useful if you're coming back, and Nassau tends to do that to people." },
      { type: "cta", text: "Start Earning HOP Moments", href: "https://app.hopbahamas.com", subtext: "Book a ride. Share a photo. Earn points toward free rides." },
    ],
    faq: [
      { q: "How do HOP Moments work?", a: "After each ride, share a photo or video from your Nassau experience through the HOP app. Photos earn 50 points, videos earn 100, and reels earn 195. Reach milestones at 250, 500, 750, and 1,000 points to unlock ride credits and rewards." },
    ],
  },

  {
    slug: "nassau-cruise-terminal-transport-guide",
    title: "Getting Around Nassau from the Cruise Terminal — The Practical Guide",
    excerpt: "Your ship docked. Here's what to do now — transportation from Nassau Cruise Terminal to every major destination, with prices and the pre-booking option most passengers don't use.",
    category: "Nassau Travel Guide",
    date: "March 18, 2026",
    readTime: "5 min read",
    featured: false,
    metaTitle: "Nassau Cruise Terminal Transportation Guide | HOP",
    metaDescription: "Transportation from Nassau Cruise Port to Atlantis, Cable Beach, Blue Lagoon, and downtown. Prices, times, and how to pre-book before your ship docks.",
    targetKeyword: "nassau cruise terminal transportation",
    content: [
      { type: "p", text: "Nassau's cruise terminal at Prince George Wharf puts you right in downtown Nassau. The Straw Market is at the exit. Bay Street is 2 minutes on foot. But Atlantis, Cable Beach, and Blue Lagoon — the places most passengers want to spend their day — are 10–25 minutes away by road." },
      { type: "p", text: "The fastest option: pre-book your transfer through HOP before your ship docks. Your driver is confirmed and waiting when you walk off the gangway. For everything else, see our complete cruise port transportation guide for pricing and timing on every option." },
      { type: "cta", text: "Pre-Book My Cruise Port Transfer", href: "https://app.hopbahamas.com", subtext: "Schedule before your ship docks. Fixed price." },
    ],
    faq: [
      { q: "How do I get from Nassau cruise port to Atlantis?", a: "Atlantis is 3.5 miles from Prince George Wharf. A taxi costs $15–$20 for 1–2 passengers and takes 10–20 minutes. Pre-book with HOP from $15 to have a driver confirmed and waiting when you dock." },
    ],
  },

  {
    slug: "hop-sos-safety-feature",
    title: "The HOP SOS System — How It Works on Every Ride",
    excerpt: "One tap starts a 3-second countdown. If not cancelled, it simultaneously calls 919, alerts HOP's Safety Desk, and texts your trusted contacts. Here's how to set it up.",
    category: "Safety",
    date: "March 12, 2026",
    readTime: "3 min read",
    featured: false,
    metaTitle: "HOP SOS Safety System — How It Works | HOP Nassau",
    metaDescription: "How HOP's SOS safety feature works on every Nassau ride. One tap contacts 919 emergency services, the HOP Safety Desk, and your trusted contacts simultaneously.",
    targetKeyword: "hop sos safety nassau",
    content: [
      { type: "p", text: "Every HOP ride comes with an SOS button that's visible the entire trip. Tap it and a 3-second countdown starts — time to cancel if it was accidental. If not cancelled, three things happen at once: Nassau's 919 emergency services are called, HOP's internal Safety Desk is alerted, and up to two trusted contacts you chose before the ride receive a notification with your live GPS location." },
      { type: "p", text: "It's not an emergency-only feature in practice. Most solo travelers use the trusted contact system on every ride as a matter of habit — the people back home can see a live map of where you are the entire time. Not because Nassau is dangerous. Because having that option costs nothing and removes a specific kind of travel anxiety." },
      { type: "h2", text: "How to Set Up Trusted Contacts" },
      { type: "ol", items: [
        "Open the HOP app and go to Safety settings",
        "Add up to 2 trusted contacts — travel partner, family member, whoever makes sense",
        "They'll receive a live tracking link for every ride you take automatically",
        "In an SOS event, they're notified immediately with your location",
      ]},
      { type: "note", text: "Trusted contacts see your location on every ride, not just during SOS events. For solo travelers with someone tracking them from home, this is the feature that actually matters." },
      { type: "cta", text: "Book a Safe Nassau Ride with HOP", href: "https://app.hopbahamas.com", subtext: "Driver verified, fare fixed, SOS ready. Every ride." },
    ],
    faq: [
      { q: "How does the HOP SOS button work?", a: "A 3-second countdown prevents accidental triggers. If not cancelled, HOP simultaneously calls Nassau 919, alerts the HOP Safety Desk, and sends your trusted contacts a notification with your live GPS location — all at once, not sequentially." },
      { q: "Do trusted contacts see my location even without an SOS?", a: "Yes. Trusted contacts receive a live tracking link for every ride you take — not just emergencies. Your travel companions or family back home can follow your route in real time the entire journey." },
    ],
  },
]

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug)
}

export function getRelatedPosts(current: BlogPost, count = 3): BlogPost[] {
  return BLOG_POSTS
    .filter((p) => p.slug !== current.slug && p.category === current.category)
    .slice(0, count)
}
